version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: api-cs-printer-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cukong_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: api-cs-printer-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_NAME: cukong_api
      DB_USER: user
      DB_PASSWORD: password
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: